/**
 * @fileoverview Command Client for Backend Communication
 * @module lib/command-client
 * 
 * FASE 4 - PASO 1: UI SHELL
 * 
 * Cliente genérico para ejecutar comandos contra el backend.
 * 
 * Reglas canónicas:
 * - La UI NUNCA asume éxito
 * - La UI NUNCA infiere permisos
 * - La UI refleja SOLO la verdad del backend
 * - Todas las acciones son comandos
 * - Los errores se muestran, nunca se ocultan
 */

import { httpsCallable } from 'firebase/functions';
import { getFirebaseFunctions } from './firebase';

// ============================================================================
// COMMAND STATE TYPES
// ============================================================================

/**
 * Command execution states.
 * 
 * CANONICAL: idle → pending → accepted / rejected
 */
export type CommandState = 'idle' | 'pending' | 'accepted' | 'rejected';

/**
 * Result from backend command execution.
 * Mirrors the backend CommandExecutionResult contract.
 */
export interface CommandResult<TReceipt = unknown> {
    /** Whether the command was accepted */
    readonly outcome: 'ACCEPTED' | 'REJECTED';

    /** The command ID for tracing */
    readonly commandId: string;

    /** Receipt payload if accepted */
    readonly receipt?: TReceipt;

    /** Rejection reason if rejected */
    readonly rejection?: {
        readonly code: string;
        readonly message: string;
        readonly stage: string;
    };
}

/**
 * State of a command execution in the UI.
 */
export interface CommandExecutionState<TReceipt = unknown> {
    /** Current state of the command */
    readonly state: CommandState;

    /** Result from backend (only after pending) */
    readonly result?: CommandResult<TReceipt>;

    /** Error if network/system failure (not rejection) */
    readonly error?: string;
}

// ============================================================================
// COMMAND CLIENT
// ============================================================================

/**
 * Command to be sent to backend.
 */
export interface Command<TPayload = unknown> {
    /** Unique command ID (generated by client) */
    readonly commandId: string;

    /** Command type (e.g., 'checklist.submit') */
    readonly commandType: string;

    /** Command payload */
    readonly payload: TPayload;

    /** Timestamp when command was issued */
    readonly issuedAt: number;

    /** Company ID (from authenticated user) */
    readonly companyId: string;
}

/**
 * Generate a unique command ID.
 */
export function generateCommandId(): string {
    const timestamp = Date.now();
    const random = Math.random().toString(36).substring(2, 10);
    return `cmd_${timestamp}_${random}`;
}

/**
 * Execute a command against the backend.
 * 
 * This function:
 * 1. Calls the backend Cloud Function
 * 2. Returns the result as-is
 * 3. NEVER interprets or modifies the result
 * 
 * @param command - The command to execute
 * @returns The command result from backend
 */
export async function executeCommand<TPayload, TReceipt>(
    command: Command<TPayload>
): Promise<CommandResult<TReceipt>> {
    const functions = getFirebaseFunctions();
    const callable = httpsCallable<Command<TPayload>, CommandResult<TReceipt>>(
        functions,
        'executeCommand'
    );

    try {
        const response = await callable(command);
        return response.data;
    } catch (error) {
        // Network or system error - NOT a backend rejection
        // We still need to report this, but it's different from a rejection
        const message = error instanceof Error ? error.message : 'Unknown error';

        // Return a synthetic rejection for network errors
        // This is NOT inferring backend state - it's reporting a transport failure
        return {
            outcome: 'REJECTED',
            commandId: command.commandId,
            rejection: {
                code: 'NETWORK_ERROR',
                message: message,
                stage: 'TRANSPORT'
            }
        };
    }
}

// ============================================================================
// HOOK HELPERS
// ============================================================================

/**
 * Initial state for command execution.
 */
export function createInitialState<TReceipt>(): CommandExecutionState<TReceipt> {
    return {
        state: 'idle'
    };
}

/**
 * Pending state for command execution.
 */
export function createPendingState<TReceipt>(): CommandExecutionState<TReceipt> {
    return {
        state: 'pending'
    };
}

/**
 * Accepted state for command execution.
 */
export function createAcceptedState<TReceipt>(
    result: CommandResult<TReceipt>
): CommandExecutionState<TReceipt> {
    return {
        state: 'accepted',
        result
    };
}

/**
 * Rejected state for command execution.
 */
export function createRejectedState<TReceipt>(
    result: CommandResult<TReceipt>
): CommandExecutionState<TReceipt> {
    return {
        state: 'rejected',
        result
    };
}
